language: node_js
node_js:
- 12
env:
- CODECOV_TOKEN=062e67b2-5aec-4fab-8455-d9819e510457
cache:
  directories:
  - node_modules
services:
- postgresql
before_script:
- npm install
- psql -c 'create database bbtest;' -U postgres
script:
- npm run test
- npm run report-test
deploy:
  provider: heroku
  api_key:
    secure: B3kX9Tlh1lY2NVyFrBV3Ckk2Fn236Pj6e0qT2vmG4SxorfDTErmBaY6U/Egd++O3eHb6FV7FHm18oqO0lyfuwfmqcK371ljlwjXJOG+D5aEtXA29k/INlXEwqIRFVhURwUVkRryg43DGboAo7nOVHKwvVk15OcTgKp3Vubh8F3H+x8g/qMHABxW+/Ci927Dr5nKDBzRr/X+uI8UhBYbKCnX2dgd3hLJ9lqHEN+lozzS8L6m0++auWP0pUKMrAg5Yov4YHO76CPgkSIAk5qhTAWaz5i8SHKoYxEFUpSqH5kaXa+IWPla4ZCl13DxDCA659yc2xD1g4DsMHQANC928Mg+/0MRZJi1UJNcldipq+TOe9aqnWqgORZrMkZOoZNSGjO8vj3S0wTKlLHMY6ya8Lde02Npt8PAuYIjdzcmQC4btazcKFzMO05RMuP7vIKbn0U35V9xmriDDFNujkzGDJokIOUGhrt5RCAQYQXLHnAuuBksd+XVfpKSLgKXx/EpuChGIPcqw6UZogXRR7lhLWrLdMwhGIqhFCLklBgr56BhOi+QysmbvMJ+tDVOnYKo3/4gYLEfrzUBeBcu/8x4jGC2ThGHB6SAcJbo4VvrUYKYCfFOZUWfazuh4OCmQvyVYnisxE6RfT5GOKBnIusbnRXPxRw2C1wG9olgFnXGGK1A=
  app: apibechdel
  on:
    repo: fac19/Bechdel-Beyond-backend
  skip_cleanup: 'true'
