language: node_js
node_js:
- 12
env:
- CODECOV_TOKEN=062e67b2-5aec-4fab-8455-d9819e510457
cache:
  directories:
  - node_modules
services:
- postgresql
before_script:
- npm install
- psql -c 'create database bbtest;' -U postgres
script:
- npm run test
- npm run report-test
deploy:
  api_key:
    secure: WaVLVQEbYwXLpG3ZrMiHcYSjwGZpdvsumTQ1X5dNg+Aj4I5kFGiVjEFSHMJK6BU55TCG0GrK5ATG9OL4dqDokJdUoYO1gGFKFQl6jPRLvLEyB7RZPrVD91xLxngBV08s/ez1LMSXygcDpegMFcrWcIcMOnGsyhKYCLVL3gKZNC6fBrWFn9DzViH4rEvLuDQ4WlXqdx4/KNCZov0xMfFRgjYBFx6UryAnAlgadpeaa9Kuc0smMq9RcVE4b3DUrWsi1bREEcRDget7h53EHCfmKm9pBRzw5k6p1UxHn1GaN7bSwWXuO8hCgUZcdwUyB0t8rnKjWCB2U9CfVuWyi9k1uTB4S8S0nM3wwcu1FECCUZ/wwysEKXSYONcK8U/6t6aZ3lWXJErk01h0b6VqCSl2YoRJ01FlHkSQ52RbEUu+0YOJzG8gIjFfVd1ZM46aBHqOrsMQna/bnyHUtlCBJvnWHF1/jbyHpU5e286OXJhF6k3Q2oMFHcHUMpQe0PEJx6DTDFYLfBTL6fPJRwf2bPew+lWt4cuVCO/1Lvau/aOCEz2TpnEimLMMw647OZOGYe8q03NAZ3vNLb0R723ZyPnv98yDjpNA3ZVzOkVpiXfUt4Fvf2O5SwSIOz50K20PtjO/Ecl/WGMu20nfeYJHRQ54Ziep3YlJgS+Oq8+vW7paa8M=
