language: node_js
node_js:
- 12
env:
- CODECOV_TOKEN=062e67b2-5aec-4fab-8455-d9819e510457
cache:
  directories:
  - node_modules
services:
- postgresql
before_script:
- npm install
- psql -c 'create database bbtest;' -U postgres
script:
- npm run test
- npm run report-test
deploy:
  provider: heroku
  api_key:
    secure: ostRJZ1TAJyllyWBE/9G965B9C0fiuBCwkI1JpOh7YTx4ujBpWs16hFFFLMAsEdjw92FSRoDtF3pwGpsk2luVyL95w43iFGfUD4Al5QAGVZbNyCTIt8fCMiTNx+nWWfQwoC0SvpY1MNEx0ilp2r++N/NuoRClHDkV5cxNNFYuK4K3s0tZl9YL0MoC9p45D2OOLGpM0ao8YgvYp//wLRvHv7skLV7VOXxn99FbR2FqvkYoBj3rFZf78L0i4lcMhG+Id0UllgmZjo/ZsCkVnKGkd4xJuT0lm4wSq7nlRfV0BenqkiPyKEAeFn3g2GyyEdM3Z0JRAe2WsuBfIL/JA+DRMBrjU6biGtDzT6mj2gMVEPuzJltv779zMx0djChjoAFHNCRYdY6cs+Ua8C/0AYNkV/BMxJJLB3HBXdF2cqfFfpv6FICAUxyF/qzigOm9wdCzTvOPSm5p9vfIn1N3seftDTnl3O7yWEibgT5ptVyIvujAoUQyBoPLhKStgMztMKCdN3w8a7pvQT49Yk3FVwNg6RxGO3yR0BC6r4msnM+3Lb6u/u5asZUrSSrpAxDTLrcz2mQSRUwaZ4wxD1lJR5wTPVWR3rXLj5BlGFdgsr9AbY3lib8PtJ6EcRei2AunPLL97pUNyxFfNWrMMB+743PNGhfmGQm+fUIgjdaMSKF0k8=
  app: apibechdel
  on:
    repo: fac19/Bechdel-Beyond-backend
  skip_cleanup: 'true'
