language: node_js
node_js:
  - 12
env:
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database bbtest;' -U postgres
script:
  - npm run test
  - npm run report-test
# deploy:
#   provider: heroku
#   api_key:
#     secure: HEROKU_API_KEY
#   app: apibechdel
#   on:
#     repo: fac19/Bechdel-Beyond-backend
#   skip_cleanup: 'true'
