language: node_js
node_js:
- 12
env:
- CODECOV_TOKEN=062e67b2-5aec-4fab-8455-d9819e510457
cache:
  directories:
  - node_modules
services:
- postgresql
before_script:
- npm install
- psql -c 'create database bbtest;' -U postgres
script:
- npm run test
- npm run report-test
deploy:
  provider: heroku
  api_key:
    secure: G7qCtGA8IeLpKQAdNoF4H+yeopkhxhvGeGdl9XMISIB1cSjbgqsNM51Y2JXzxCT48OA3TrjZDWiIR3d8Hx25CV/USfWyQprhMTEhJURkHNWBwmg0h+bmm4Jq/niP3B3w0Gu75mTU5zQnhNVf6NZP9Tbw0t37qRwjZJhB8GFRVW1OCqEW/qneyhBE5cQUsamCppLJtnTjzeBzSgdELnu4XUcNLscnjzCOORPyMWLoWdWIq5buR+Xq8lnCYa/PAEobFnmj3rJmo9TDjoC8s51z0illlEP/jal7kDRQNevIEx8cZXrD5WNfPQDeSxFIIl84qJ3+hLzRgAueur+GrC6b+qIZZKL+3rn3/hXX4Md61zRQbLdy2PxPGLv0Nh+CbYXw8hv6Jwub3f1YpGBbBY9pt4R7K2++2tO9eXVxe7NwfdjMUI3fIQ1HpgxGoPegUIm8iuqNZedLyDrhnFKdDUinpiiolyLxFOlacERXADBZ3yIue2KjGIm9rGKi0D9VQzsmexpE5vZx7gO45jmQ8Mo89E3aMLgwwcWaYHpDamQXnUbQSQeiRBRe47NkDDaOHC/BUL9h2fOSXGBGS7UTEMmBXtp3CbZrEgbqRAQBcSwja0H6YrIibZhwICwsI4XwOF3INbBKKm2usmOHN3HG4wVpBkB5yYqdY6ED3Yj0r1FHAgI=
  app: Bechdel-Beyond-backend
  on:
    repo: fac19/Bechdel-Beyond-backend
  skip_cleanup: 'true'
